In [ ]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
from networkx.algorithms import community as nxcm
from sklearn.cluster import KMeans
from networkx import edge_betweenness_centrality as betweenness
from itertools import chain, combinations
from scipy.cluster.hierarchy import dendrogram
from datetime import datetime
import numpy as np
from scipy import stats

In [ ]:
#Reading karate Club Network
G = nx.read_gml('karate.gml', label = 'id')
#Reading Dolphins network
H = nx.read_gml('dolphins.gml', label = 'id')
#Reading Jazz Netwrok
fh=open("jazz.net", "rb")
I = nx.read_weighted_edgelist(fh)

In [ ]:
#Girvan-Newman for Karate network
def most_central_edge(G):
    centrality = betweenness(G, weight="weight")
    return max(centrality, key=centrality.get)

comp_GN = nxcm.girvan_newman(G, most_valuable_edge=most_central_edge)
first_division=next(comp_GN);
print(sorted(first_division))


communities = list(nx.community.girvan_newman(G))

[{1, 2, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18, 20, 22}, {3, 9, 10, 15, 16, 19, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34}]


In [ ]:
#Representative network for Karate
number_of_clusters = len(first_division)

adjacency_matrix = np.zeros(shape=(number_of_clusters,number_of_clusters))

for u,v,a in G.edges(data=True):
  u_location=-1
  v_location=-1
  for i in range(0,number_of_clusters):
    if(u in first_division[i]):
      u_location=i;
    if(v in first_division[i]):
      v_location=i;
  
  #print(u," ", v, " ",u_location," ", v_location)
  if(u_location!=v_location):
    adjacency_matrix[u_location][v_location]+=1;
    adjacency_matrix[v_location][u_location]+=1;
  
print(adjacency_matrix)

representative_network = nx.from_numpy_matrix(adjacency_matrix)
nx.write_gexf(representative_network, "test.gexf")

[[ 0. 10.]
 [10.  0.]]


In [ ]:
#Girvan-Newman for  Dolphins
def most_central_edge(G):
    centrality = betweenness(G, weight="weight")
    return max(centrality, key=centrality.get)
comp_GN = nxcm.girvan_newman(H, most_valuable_edge=most_central_edge)
communities = list(nx.community.girvan_newman(H))
print(communities[3])
first_division=communities[3]
print(sorted(first_division))

({0, 2, 10, 42, 47, 28, 30}, {1, 5, 6, 7, 9, 13, 17, 19, 22, 25, 26, 27, 31, 32, 39, 41, 48, 54, 56, 57, 60}, {3, 8, 12, 14, 16, 20, 33, 34, 36, 37, 38, 40, 43, 44, 46, 49, 50, 52, 58, 59}, {35, 4, 11, 45, 15, 18, 51, 23, 21, 55, 24, 29}, {61, 53})
[{0, 2, 10, 42, 47, 28, 30}, {1, 5, 6, 7, 9, 13, 17, 19, 22, 25, 26, 27, 31, 32, 39, 41, 48, 54, 56, 57, 60}, {3, 8, 12, 14, 16, 20, 33, 34, 36, 37, 38, 40, 43, 44, 46, 49, 50, 52, 58, 59}, {35, 4, 11, 45, 15, 18, 51, 23, 21, 55, 24, 29}, {61, 53}]


In [ ]:
#Representative network for Dolphins network
number_of_clusters = len(first_division)

adjacency_matrix = np.zeros(shape=(number_of_clusters,number_of_clusters))

for u,v,a in G.edges(data=True):
  u_location=-1
  v_location=-1
  for i in range(0,number_of_clusters):
    if(u in first_division[i]):
      u_location=i;
    if(v in first_division[i]):
      v_location=i;
  
  #print(u," ", v, " ",u_location," ", v_location)
  if(u_location!=v_location):
    adjacency_matrix[u_location][v_location]+=1;
    adjacency_matrix[v_location][u_location]+=1;
  
print(adjacency_matrix)

representative_network = nx.from_numpy_matrix(adjacency_matrix)
nx.write_gexf(representative_network, "test1.gexf")

[[ 0.  5. 10.  4.  0.]
 [ 5.  0. 15.  8.  0.]
 [10. 15.  0. 13.  0.]
 [ 4.  8. 13.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [ ]:
#Girvan-Newman for Jazz
def most_central_edge(G):
    centrality = betweenness(G, weight="weight")
    return max(centrality, key=centrality.get)

comp_GN = nxcm.girvan_newman(I, most_valuable_edge=most_central_edge)
communities = list(nx.community.girvan_newman(G))
print(communities[3])
first_division=communities[3]
print(sorted(first_division))

({1, 2, 4, 8, 12, 13, 14, 18, 20, 22}, {32, 3, 25, 26, 28, 29}, {5, 6, 7, 11, 17}, {33, 34, 9, 15, 16, 19, 21, 23, 24, 27, 30, 31}, {10})
[{1, 2, 4, 8, 12, 13, 14, 18, 20, 22}, {32, 3, 25, 26, 28, 29}, {5, 6, 7, 11, 17}, {33, 34, 9, 15, 16, 19, 21, 23, 24, 27, 30, 31}, {10}]


In [ ]:
#Representative Network for Jazz musicians Network
#Consider the GN Method as the community detection method and then generating the representative graph

number_of_clusters = len(first_division)

adjacency_matrix = np.zeros(shape=(number_of_clusters,number_of_clusters))

for u,v,a in G.edges(data=True):
  u_location=-1
  v_location=-1
  for i in range(0,number_of_clusters):
    if(u in first_division[i]):
      u_location=i;
    if(v in first_division[i]):
      v_location=i;
  
  #print(u," ", v, " ",u_location," ", v_location)
  if(u_location!=v_location):
    adjacency_matrix[u_location][v_location]+=1;
    adjacency_matrix[v_location][u_location]+=1;
  
print(adjacency_matrix)

representative_network = nx.from_numpy_matrix(adjacency_matrix)
nx.write_gexf(representative_network, "jazz.gexf")
#representative_network = nx.from_numpy_matrix(adjacency_matrix, create_using=nx.DiGraph)
#layout = nx.spring_layout(representative_network)
#labels = nx.get_edge_attributes(representative_network, "weight")
#nx.draw(representative_network, layout)
#nx.draw_networkx_edge_labels(representative_network, pos=layout, edge_labels=labels)
#plt.show()



[[0. 1. 0. 0. 0.]
 [1. 0. 6. 1. 1.]
 [0. 6. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
